/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvasteetRouteImport } from './routes/evasteet'
import { Route as HinnastoRouteImport } from './routes/hinnasto'
import { Route as KayttoehdotRouteImport } from './routes/kayttoehdot'
import { Route as KiitosRouteImport } from './routes/kiitos'
import { Route as MinustaRouteImport } from './routes/minusta'
import { Route as MitenToimimmeRouteImport } from './routes/miten-toimimme'
import { Route as PalvelutRouteImport } from './routes/palvelut'
import { Route as SaavutettavuusRouteImport } from './routes/saavutettavuus'
import { Route as TietosuojaRouteImport } from './routes/tietosuoja'
import { Route as UkkRouteImport } from './routes/ukk'
import { Route as YhteystiedotRouteImport } from './routes/yhteystiedot'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvasteetRoute = EvasteetRouteImport.update({
  id: '/evasteet',
  path: '/evasteet',
  getParentRoute: () => rootRouteImport,
} as any)
const HinnastoRoute = HinnastoRouteImport.update({
  id: '/hinnasto',
  path: '/hinnasto',
  getParentRoute: () => rootRouteImport,
} as any)
const KayttoehdotRoute = KayttoehdotRouteImport.update({
  id: '/kayttoehdot',
  path: '/kayttoehdot',
  getParentRoute: () => rootRouteImport,
} as any)
const KiitosRoute = KiitosRouteImport.update({
  id: '/kiitos',
  path: '/kiitos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinustaRoute = MinustaRouteImport.update({
  id: '/minusta',
  path: '/minusta',
  getParentRoute: () => rootRouteImport,
} as any)
const MitenToimimmeRoute = MitenToimimmeRouteImport.update({
  id: '/miten-toimimme',
  path: '/miten-toimimme',
  getParentRoute: () => rootRouteImport,
} as any)
const PalvelutRoute = PalvelutRouteImport.update({
  id: '/palvelut',
  path: '/palvelut',
  getParentRoute: () => rootRouteImport,
} as any)
const SaavutettavuusRoute = SaavutettavuusRouteImport.update({
  id: '/saavutettavuus',
  path: '/saavutettavuus',
  getParentRoute: () => rootRouteImport,
} as any)
const TietosuojaRoute = TietosuojaRouteImport.update({
  id: '/tietosuoja',
  path: '/tietosuoja',
  getParentRoute: () => rootRouteImport,
} as any)
const UkkRoute = UkkRouteImport.update({
  id: '/ukk',
  path: '/ukk',
  getParentRoute: () => rootRouteImport,
} as any)
const YhteystiedotRoute = YhteystiedotRouteImport.update({
  id: '/yhteystiedot',
  path: '/yhteystiedot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evasteet': typeof EvasteetRoute
  '/hinnasto': typeof HinnastoRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kiitos': typeof KiitosRoute
  '/minusta': typeof MinustaRoute
  '/miten-toimimme': typeof MitenToimimmeRoute
  '/palvelut': typeof PalvelutRoute
  '/saavutettavuus': typeof SaavutettavuusRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evasteet': typeof EvasteetRoute
  '/hinnasto': typeof HinnastoRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kiitos': typeof KiitosRoute
  '/minusta': typeof MinustaRoute
  '/miten-toimimme': typeof MitenToimimmeRoute
  '/palvelut': typeof PalvelutRoute
  '/saavutettavuus': typeof SaavutettavuusRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evasteet': typeof EvasteetRoute
  '/hinnasto': typeof HinnastoRoute
  '/kayttoehdot': typeof KayttoehdotRoute
  '/kiitos': typeof KiitosRoute
  '/minusta': typeof MinustaRoute
  '/miten-toimimme': typeof MitenToimimmeRoute
  '/palvelut': typeof PalvelutRoute
  '/saavutettavuus': typeof SaavutettavuusRoute
  '/tietosuoja': typeof TietosuojaRoute
  '/ukk': typeof UkkRoute
  '/yhteystiedot': typeof YhteystiedotRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evasteet'
    | '/hinnasto'
    | '/kayttoehdot'
    | '/kiitos'
    | '/minusta'
    | '/miten-toimimme'
    | '/palvelut'
    | '/saavutettavuus'
    | '/tietosuoja'
    | '/ukk'
    | '/yhteystiedot'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evasteet'
    | '/hinnasto'
    | '/kayttoehdot'
    | '/kiitos'
    | '/minusta'
    | '/miten-toimimme'
    | '/palvelut'
    | '/saavutettavuus'
    | '/tietosuoja'
    | '/ukk'
    | '/yhteystiedot'
  id:
    | '__root__'
    | '/'
    | '/evasteet'
    | '/hinnasto'
    | '/kayttoehdot'
    | '/kiitos'
    | '/minusta'
    | '/miten-toimimme'
    | '/palvelut'
    | '/saavutettavuus'
    | '/tietosuoja'
    | '/ukk'
    | '/yhteystiedot'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvasteetRoute: typeof EvasteetRoute
  HinnastoRoute: typeof HinnastoRoute
  KayttoehdotRoute: typeof KayttoehdotRoute
  KiitosRoute: typeof KiitosRoute
  MinustaRoute: typeof MinustaRoute
  MitenToimimmeRoute: typeof MitenToimimmeRoute
  PalvelutRoute: typeof PalvelutRoute
  SaavutettavuusRoute: typeof SaavutettavuusRoute
  TietosuojaRoute: typeof TietosuojaRoute
  UkkRoute: typeof UkkRoute
  YhteystiedotRoute: typeof YhteystiedotRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evasteet': {
      id: '/evasteet'
      path: '/evasteet'
      fullPath: '/evasteet'
      preLoaderRoute: typeof EvasteetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinnasto': {
      id: '/hinnasto'
      path: '/hinnasto'
      fullPath: '/hinnasto'
      preLoaderRoute: typeof HinnastoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kayttoehdot': {
      id: '/kayttoehdot'
      path: '/kayttoehdot'
      fullPath: '/kayttoehdot'
      preLoaderRoute: typeof KayttoehdotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiitos': {
      id: '/kiitos'
      path: '/kiitos'
      fullPath: '/kiitos'
      preLoaderRoute: typeof KiitosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minusta': {
      id: '/minusta'
      path: '/minusta'
      fullPath: '/minusta'
      preLoaderRoute: typeof MinustaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miten-toimimme': {
      id: '/miten-toimimme'
      path: '/miten-toimimme'
      fullPath: '/miten-toimimme'
      preLoaderRoute: typeof MitenToimimmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palvelut': {
      id: '/palvelut'
      path: '/palvelut'
      fullPath: '/palvelut'
      preLoaderRoute: typeof PalvelutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saavutettavuus': {
      id: '/saavutettavuus'
      path: '/saavutettavuus'
      fullPath: '/saavutettavuus'
      preLoaderRoute: typeof SaavutettavuusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tietosuoja': {
      id: '/tietosuoja'
      path: '/tietosuoja'
      fullPath: '/tietosuoja'
      preLoaderRoute: typeof TietosuojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ukk': {
      id: '/ukk'
      path: '/ukk'
      fullPath: '/ukk'
      preLoaderRoute: typeof UkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/yhteystiedot': {
      id: '/yhteystiedot'
      path: '/yhteystiedot'
      fullPath: '/yhteystiedot'
      preLoaderRoute: typeof YhteystiedotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvasteetRoute: EvasteetRoute,
  HinnastoRoute: HinnastoRoute,
  KayttoehdotRoute: KayttoehdotRoute,
  KiitosRoute: KiitosRoute,
  MinustaRoute: MinustaRoute,
  MitenToimimmeRoute: MitenToimimmeRoute,
  PalvelutRoute: PalvelutRoute,
  SaavutettavuusRoute: SaavutettavuusRoute,
  TietosuojaRoute: TietosuojaRoute,
  UkkRoute: UkkRoute,
  YhteystiedotRoute: YhteystiedotRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
